### ISSUE TITLE
Plotting points at the ternary diagram border

### ISSUE THREAD

**Issue by mcomas** [nicholasehamilton/ggtern#29]
Is it possible to completely plot a point close to the border? When I try

```
ggtern() + geom_point(aes(x = 1, y = 0, z = 0), size=10)
```

the point appears partially. I've tried to modifiy option `tern.discard.external` to `FALSE` 
but the point is still partially plotted.

**Comment by fojxl** [comment]
Add geom_mask()...

ggtern() + geom_mask() + geom_point(aes(x = 1, y = 0, z = 0), size=10)

**Comment by mcomas** [comment]
It works perfectly, thank you!!!
